name: Frontend Workflow
on:
  push:
    branches: [main]
    paths:
      - "frontend/**"
  workflow_dispatch:

jobs:
  build-deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # or '20'
          cache: npm
          cache-dependency-path: frontend/my-app/package-lock.json

      - name: Install dependencies
        run: cd frontend/my-app && npm ci

      - name: Build React app
        run: cd frontend/my-app && npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Sync build to S3
        run: aws s3 sync frontend/my-app/build s3://${{ secrets.S3_BUCKET }} --delete
